version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -U deploy 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - run.sh
  discard-paths: yes
